name: Build Android WebView App

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Zip APK
        run: |
          cd app/build/outputs/apk/debug
          zip -r webview-app.zip app-debug.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: webview-app
          path: app/build/outputs/apk/debug/webview-app.zip